version: '3.8'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: stack2-mern-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: trello
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - trello-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stack2-mern-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongodb:27017/trello
      NODE_ENV: development
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - trello-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stack2-mern-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://backend:5000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - trello-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  trello-network:
    driver: bridge

volumes:
  mongodb_data:
